import {useState} from 'react';
import {invoke,host} from './bridge.ts';
import {Modal} from './components.tsx';
import type {Song,Source} from './model.ts';
export function AIPanel({songs,sources,setSources,onPlaylist,notify,current}: {songs: Song[];sources: Source[];setSources:(rows:Source[])=>void;onPlaylist:(ids:string[])=>void;notify:(text:string)=>void;current?:Song}) {
 const [editing,setEditing]=useState<Source|'new'|null>(null);const [prompt,setPrompt]=useState('为我推荐一份适合现在听的歌单');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [ids,setIds]=useState<string[]>([]);const providers=sources.filter(s=>s.type==='ai');
 async function ask(provider:Source,explain=false){setBusy(true);setIds([]);try{
  const library=songs.slice(0,1000).map(s=>({id:s.id,title:s.title,artist:s.artist,album:s.album}));
  const text=explain&&current ? `请解读这首歌曲，区分可确认事实与个人理解：${JSON.stringify({title:current.title,artist:current.artist,album:current.album,lyrics:current.lyrics?.slice(0,6000)})}` : `${prompt}\n只从以下曲库推荐，返回 JSON {"explanation":"推荐原因","songIds":["已有歌曲id"]}，最多 30 首。曲库：${JSON.stringify(library)}`;
  const result=await invoke<string>('ai.request',{sourceId:provider.id,prompt:text});setAnswer(result);
  if(!explain){try{const parsed=JSON.parse(result.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));const available=new Set(songs.map(s=>s.id));setIds([...new Set<string>((parsed.songIds || []).filter((id:unknown)=>typeof id==='string'&&available.has(id)).slice(0,30))]);if(typeof parsed.explanation==='string')setAnswer(parsed.explanation);}catch{}}
 }catch(e){notify(String(e));}finally{setBusy(false);}}
 return <div className="ai-view"><p className="muted">点击发送会将所选曲目信息或曲库前 1000 首的名称、艺术家与专辑发送给你配置的 AI 服务。音频和服务器密码不会发送。推荐只使用当前曲库中的歌曲。</p>
 <button className="primary" disabled={host.platform==='browser'} onClick={()=>setEditing('new')}>添加 AI 服务</button><label>推荐需求<textarea aria-label="推荐需求" rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>
 {providers.map(provider=><div className="source-row" key={provider.id}><div><strong>{provider.name}</strong><small>{provider.model} · {provider.protocol || 'openai'}</small></div><button disabled={busy} onClick={()=>void ask(provider)}>生成推荐</button><button disabled={busy||!current} onClick={()=>void ask(provider,true)}>解读当前歌曲</button><button onClick={()=>setEditing(provider)}>编辑</button><button onClick={async()=>{try{await invoke('sources.remove',{id:provider.id});setSources(sources.filter(s=>s.id!==provider.id));}catch(e){notify(String(e));}}}>删除</button></div>)}
 {busy?<p role="status">正在等待 AI 服务…</p>:null}{answer?<div className="ai-answer">{answer}</div>:null}{ids.length?<button className="primary" onClick={()=>{onPlaylist(ids);notify(`已创建 AI 推荐歌单，${ids.length} 首`);}}>保存推荐歌单 · {ids.length} 首</button>:null}
 {editing?<Modal title="AI 服务配置" close={()=>setEditing(null)}><form onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{const source=await invoke<Source>('sources.save',{...values,id:editing==='new'?crypto.randomUUID():editing.id,type:'ai',username:''});setSources([...sources.filter(s=>s.id!==source.id),source]);setEditing(null);}catch(e){notify(String(e));}}}>
 <label>名称<input name="name" required defaultValue={editing==='new'?'我的 AI':editing.name}/></label><label>接口协议<select name="protocol" defaultValue={editing==='new'?'openai':editing.protocol}><option value="openai">OpenAI 兼容 / DeepSeek</option><option value="anthropic">Anthropic</option></select></label><label>Base URL<input name="url" type="url" required placeholder="https://api.example.com/v1/" defaultValue={editing==='new'?'':editing.url}/></label><label>模型<input name="model" required defaultValue={editing==='new'?'':editing.model}/></label><label>API Key<input name="password" type="password" placeholder={editing==='new'?'':'留空保留原 Key'}/></label><p className="muted">Key 使用系统安全存储。此处填写服务根路径，程序追加 messages 或 chat/completions。</p><button className="primary" type="submit">保存服务</button></form></Modal>:null}</div>;
}
